# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaceOverride: "cla-mssql-nfs"

replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-CU16-GDR1-ubuntu-20.04"

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Express"
MSSQL_AGENT_ENABLED:
    value: "false"

hadrEnabled: 0

containers:
  ports:
      containerPort: 1433

podAnnotations: {}

podSecurityContext:
   fsGroup: 10001

service:
  port: 1433

storageClassName: nfs-client-mssql
  
storageCapacity: 10Gi