version: "3.8"
services:
  
  pg13:
    container_name: pg13
    image: "bitnami/postgresql:13.4.0-debian-10-r19"
    mem_limit: 3g
    ports:
      - "6432:5432"
    volumes:
      - /Docker/pg13:/bitnami/postgresql
      - /Docker/pg13-init:/docker-entrypoint-initdb.d
      - /Docker/pg13-preinit:/docker-entrypoint-preinitdb.d
      - /Docker/pg13conf/:/bitnami/postgresql/conf/
      - /Docker/pg13basebackup:/basebackup
    env_file: pg13localenv