# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cla-pg-volume
#   labels:
#     type: local
#     app: cla-pg
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: "/k8-pv/pg"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - kind-worker
#---
apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: cla-pg-nfs-pv # Sets PV name
  labels:
    type: local # Sets PV's type
    app: cla-pg-nfs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8-nsf/kind-nfs
    server: 172.10.250.75