apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-0
  namespace: {{ .Values.namespaceOverride | default "default" }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mssql-sql-statefull-deploy-0
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-1
  namespace: {{ .Values.namespaceOverride | default "default" }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mssql-sql-statefull-deploy-1
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-2
  namespace: {{ .Values.namespaceOverride | default "default" }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mssql-sql-statefull-deploy-2
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
