version: "3.8"
services:
  
  pg9:
    container_name: pg9
    image: "docker.io/bitnami/postgresql:9.6"
    mem_limit: 2g
    mem_reservation: 256m
    ports:
      - "7432:5432"
    volumes:
      - /docker/pg/pg9-data:/bitnami/postgresql
      - /docker/pg/pg9-init:/docker-entrypoint-initdb.d
      - /docker/pg/pg9-preinit:/docker-entrypoint-preinitdb.d
      - /docker/pg/pg9-conf/:/bitnami/postgresql/conf/
    env_file: pg9env
    restart: always