kind: Namespace
apiVersion: v1
metadata:
  name: cla-pg-ha
  labels:
    name: cla-pg-ha
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cla-pg-ha-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8-nsf/cla-postgres-ha
    server: 172.10.250.75
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cla-pg-ha
  name: cla-pg-ha-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: cla-pg-ha-pv