kind: Namespace
apiVersion: v1
metadata:
  name: cla-pg-ha
  labels:
    name: cla-pg-ha
---
apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: cla-pg-ha-pv # Sets PV name
  namespace: cla-pg-ha
  labels:
    type: local # Sets PV's type
    app: cla-pg-ha
spec:
  capacity:
    storage: 50Gi # Sets PV's size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/k8-pv/pg-ha" # Sets PV's host path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - db-node01
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: cla-pg-ha-pvc # Sets PVC's name
  namespace: cla-pg-ha
  labels:
    app: cla-pg-ha # Defines app to create PVC for
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Sets PVC's size