kind: Namespace
apiVersion: v1
metadata:
  name: cla-pg-ha
  labels:
    name: cla-pg-ha
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cla-local-storage
  namespace: cla-pg-ha
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cla-pv-local-storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: cla-local-storage
  local:
    path: /k8-pv/pg-ha
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - db-node02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cla-pvc-local
  namespace: cla-pg-ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cla-local-storage
  resources:
    requests:
      storage: 5Gi