kind: Namespace
apiVersion: v1
metadata:
  name: cla-pg-ha
  labels:
    name: cla-pg-ha
---
apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: cla-pg-ha-pv # Sets PV name
  namespace: cla-pg-ha
  labels:
    type: local # Sets PV's type
    app: cla-pg-ha
spec:
  capacity:
    storage: 100Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8-pv/pg" # Sets PV's host path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: cla-pg-ha-pvc # Sets PVC's name
  namespace: cla-pg-ha
  labels:
    app: cla-pg-ha # Defines app to create PVC for
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Sets PVC's size