kind: Namespace
apiVersion: v1
metadata:
  name: cla-pg
  labels:
    name: cla-pg
---
# Create ConfigMap postgres-secret for the postgres app
# Define default database name, user, and password
apiVersion: v1
kind: ConfigMap
metadata:
  name: cla-pg-secret
  namespace: cla-pg
  labels:
    app: cla-pg
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: Abcd1234
---
apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: cla-pg-postgres-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: cla-pg
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8-pv/pg" # Sets PV's host path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: cla-pg-postgres-volume-claim # Sets PVC's name
  namespace: cla-pg
  labels:
    app: cla-pg # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi # Sets PVC's size
---
apiVersion: v1
kind: Service # Create service
metadata:
  name: cla-pg-svc # Sets the service name
  namespace: cla-pg
  labels:
    app: cla-pg # Defines app to create service for
spec:
  type: NodePort # Sets the service type
  ports:
    - port: 9432 # Sets the port to run the postgres application
  selector:
    app: cla-pg
---
apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  namespace: cla-pg
  name: cla-pg # Set the name of the deployment
spec:
  replicas: 2 # Set 2 deployment replicas
  selector:
    matchLabels:
      app: cla-pg
  template:
    metadata:
      labels:
        app: cla-pg
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:13.7.0-debian-11-r7 # Docker image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: cla-pg-secret # Using the ConfigMap postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cla-pg-postgresdata
      volumes:
        - name: cla-pg-postgresdata
          persistentVolumeClaim:
            claimName: cla-pg-postgres-volume-claim