apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cla-pg-nfs       
  name: fakepod
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
          runAsUser: 1028
          runAsGroup: 1028
          fsGroup: 1028
      containers:
      - name: test
        image: busybox
        ports:
        - containerPort: 80
        command: [ "sh", "-c", "sleep 1h" ]
        volumeMounts:
          - name: cla-pg-nfs-postgresdata
            mountPath: /opt/nfs
      volumes:
        - name: cla-pg-nfs-postgresdata
          persistentVolumeClaim:
            claimName: cla-pg-nfs-pvc
