apiVersion: v1
kind: Namespace
metadata:
  name: cla-fake
  labels:
    name: cla-fake
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cla-pg-secret
  namespace: cla-fake
data:
  POSTGRESQL_USERNAME: userk8
  POSTGRESQL_PASSWORD: pwdk8
  POSTGRESQL_DATABASE: TestDatabase
  POSTGRESQL_POSTGRES_PASSWORD: Abcd1234
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cla-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8-nsf/cla-fake-postgres
    server: 172.10.250.75
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cla-pvc
  namespace: cla-fake
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Sets PVC's size
  volumeName: cla-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cla-fake
  name: fakepod
  labels:
    app: test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
        runAsUser: 1028
        runAsGroup: 100
        fsGroup: 100
      containers:
      - name: test
        image: busybox
        ports:
        - containerPort: 80
        command: [ "sh", "-c", "sleep 1h" ]
        volumeMounts:
          - name: cla-fake-nfs
            mountPath: /opt/nfs
      volumes:
        - name: cla-fake-nfs
          persistentVolumeClaim:
            claimName: cla-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth-0 
  namespace: cla-fake
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30002
  selector:
    app.kubernetes.io/name: sawtooth-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cla-fake
  name: sawtooth-0
  labels:
    app: cla-fake-pg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sawtooth-0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sawtooth-0
    spec:
      securityContext:
        fsGroup: 100        
      containers:
        - name: postgres
          image: bitnami/postgresql:13.7.0-debian-11-r7
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: cla-pg-secret
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: cla-pg-postgresdata
      volumes:
        - name: cla-pg-postgresdata
          persistentVolumeClaim:
            claimName: cla-pvc