apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cla-pg-nfs       
  name: fakepod
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
      containers:
      - name: test
        image: busybox
        ports:
        - containerPort: 80
        command: [ "sh", "-c", "sleep 1h" ]
        volumeMounts:
          - name: nfs-vol
            mountPath: /opt/nfs
      volumes:
        - name: nfs-vol
          nfs:
            server: 172.10.250.75
            path: /volume1/k8-nfs
