apiVersion: v1
kind: Namespace
metadata:
  name: cla-pg-gluster
  labels:
    name: cla-pg-gluster
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: cla-pg-gluster
  labels:
    storage.k8s.io/name: glusterfs
    storage.k8s.io/part-of: kubernetes-complete-reference
subsets:
  - addresses:
      - ip: 172.104.250.37
        hostname: db-node01
      - ip: 172.104.250.38
        hostname: db-node02
      - ip: 172.104.250.39
        hostname: db-node03
    ports:
      - port: 49152
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: cla-pg-gluster
spec:
  ports:
  - port: 49152
    protocol: TCP
    targetPort: 49152
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cla-pg-gluster-secret
  namespace: cla-pg-gluster
  labels:
    app: cla-pg-gluster
data:
  POSTGRESQL_USERNAME: userk8
  POSTGRESQL_PASSWORD: pwdk8
  POSTGRESQL_DATABASE: TestDatabase
  POSTGRESQL_POSTGRES_PASSWORD: Abcd1234
---
apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: cla-pg-gluster-v # Sets PV name
  labels:
    storage.k8s.io/name: glusterfs      
    storage.k8s.io/part-of: kubernetes-complete-reference      
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8-volume
    readOnly: no
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: cla-pg-gluster-v # Sets PVC's name
  namespace: cla-pg-gluster
  labels:
    app: cla-pg-gluster # Defines app to create PVC for
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Sets PVC's size
