web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'ubuntu2004.wsl'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://ubuntu2004.wsl'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '~/gitlab/config:/etc/gitlab'
    - '~/gitlab/logs:/var/log/gitlab'
    - '~/gitlab/data:/var/opt/gitlab'